model:
    backbone: resnet18
    layers:
      - layer2
      - layer3
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
data:
    root: ./datasers/MVTecAD
    category: bottle
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 2
mlflow:
    expirement_name: visual defect inspector
engine:
    max_epochs: 1
    enable_progress_bar: false
    enable_model_summary: false
    logger: false
artifacts: 
    save_dir: ./saved_model